version: '3'

services:

  # PostgreSQL
  dbk:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: terrasystem1
      POSTGRES_DB: kriolstockdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    networks:
#      - backend

  # Django REST API
  django:
    build:
      context: .
      dockerfile: ./kriolstock_dapi/Dockerfile
    container_name: django_app
    volumes:
      - ./kriolstock_dapi:/app
    ports:
      - "8001:8001"
    depends_on:
      - dbk
    restart: always
    networks:
      - backend

  # Frontend with Next.js (React)
  frontend:
    build:
      context: ../kriolstock-web
      dockerfile: ./Dockerfile
    container_name: nextjs_frontend
    volumes:
      - ../kriolstock-web:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    restart: always
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  pg_data:
